//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//// WARNING: Boilerplate to prevent baseline compilation errors ////

//
// This file was generated by the tool translation-resource-generator.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//
namespace Roblox.TranslationResources;

/// <summary>
/// Provider for all translation resources.
/// </summary>
public class MasterResources : global::Roblox.TranslationResources.IMasterResources
{
    private readonly global::System.Collections.Generic.IReadOnlyCollection<global::Roblox.TranslationResources.ITranslationResourcesNamespacesGroup> _TranslationResourcesNamespacesGroups;

    /// <summary>
    /// Initializes a new instance of the <see cref="MasterResources"/> class.
    /// </summary>
    /// <param name="locale">The locale to use.</param>
    /// <param name="state">The state to use.</param>
    public MasterResources(global::Roblox.TranslationResources.TranslationResourceLocale locale, global::Roblox.TranslationResources.TranslationResourceState state)
        : this(
        )
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="MasterResources"/> class.
    /// </summary>
    /// <exception cref="global::System.ArgumentNullException">
    /// </exception>
    internal MasterResources(
    )
    {

        _TranslationResourcesNamespacesGroups = new global::Roblox.TranslationResources.ITranslationResourcesNamespacesGroup[]
        {
        };
    }

    /// <summary>
    /// Gets the <see cref="global::Roblox.TranslationResources.ITranslationResources"/> instance for the given full namespace.
    /// </summary>
    /// <param name="fullTranslationResourceNamespace">The full translation resource namespace.</param>
    /// <returns>The <see cref="global::Roblox.TranslationResources.ITranslationResources"/> instance.</returns>
    public global::Roblox.TranslationResources.ITranslationResources GetTranslationResourcesByFullNamespace(string fullTranslationResourceNamespace)
    {
        foreach (var group in _TranslationResourcesNamespacesGroups)
        {
            var translationResources = group.GetByFullNamespace(fullTranslationResourceNamespace);
            if (translationResources != null) return translationResources;
        }

        return null;
    }
}
