//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//// WARNING: Boilerplate to prevent baseline compilation errors ////

//
// This file was generated by the tool translation-resource-generator.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//
namespace Roblox.TranslationResources;

/// <summary>
/// Provider for all translation resources.
/// </summary>
public interface IMasterResources
{

    /// <summary>
    /// Gets the translation resources for the specified full namespace.
    /// </summary>
    /// <param name="fullTranslationResourceNamespace">The full namespace of the translation resources.</param>
    /// <returns>The translation resources for the specified full namespace.</returns>
    global::Roblox.TranslationResources.ITranslationResources GetTranslationResourcesByFullNamespace(string fullTranslationResourceNamespace);
}
